### ISSUE TITLE
Closing the portal immediately after use

### ISSUE THREAD

**Issue by rtgxjzgsryksryydtyrkry** [RafalBerezin/Pocket_Dimension#1]
I'm a server admin, it would be cool to have a personal dimension, but if everyone can log into it, it's not so cool anymore. I would like the portal to close immediately after use.

Make cooldown 3 seconds instead of 20/check OP before teleporting/close portal immediately after use

I tried to modify the datapack, but I could only change the portal texture

Also, I poked something in the settings, I have 2 bedrock platforms in overworld, and now I’m instantly killed as soon as I respawn, funny.

**Comment by rtgxjzgsryksryydtyrkry** [comment]
Also teleport only ones holding Tesseract

**Comment by rtgxjzgsryksryydtyrkry** [comment]
Okay, in general, I recoded everything that I needed. The only thing is that I want to make sure that the player always ends up on x0 y0 z0, so that you can invite people to the admin dimension. I didn’t really understand how to remove the UUID-based coordinate system

**Comment by rtgxjzgsryksryydtyrkry** [comment]
Ok, I just deleted UUID[0] and UUID[1], works just fine, 0 0 0 co-ords

**Comment by RafalBerezin** [comment]
Great that you managed to figure it out. Also this gave me an idea. I could add a per player switch to make make your pocket private. Let me know if you like it or if you have any other ideas.

**Comment by rtgxjzgsryksryydtyrkry** [comment]
[PD_m.zip](https://github.com/RafalBerezin/Pocket_Dimension/files/14590785/PD_m.zip)

Here is a modified version of the datapack, if you are interested, the 3D model and textures were quickly made for my project (server for friends)

**Comment by rtgxjzgsryksryydtyrkry** [comment]
Here the animation of the portal has been changed to 3D, 3D model, texture, effects, the teleportation point is always 0 0 0, added the sound of an explosion for “coolness”, now to get into the dimension you need to hold the command block with the enchantment in offhand

**Comment by rtgxjzgsryksryydtyrkry** [comment]
Oh, also several exit points, like co-ords

**Comment by rtgxjzgsryksryydtyrkry** [comment]
I found a rather strange way to implement different coordinates, but to change them, you will have to restart the datapack, and also have a 2nd condition to be executed so that the clear function is not executed, without cutting it out. I don't know what could happen if I cut it out, I'm not going to test it. 
It works through an additional execute, which refers to a duplicate of the charge function, which refers to a duplicate of macro_positioning, which refers to a duplicate of teleport(portal), the latter changes the coordinates from tp ~ ~ ~ to the required ones.
You need a key to get into the dimension + an additional item indicating the coordinates through a duplicate predicate (you cannot use anything other than an item with coordinates ~ ~ ~ to enter the pocket, otherwise you will fall into the void). To exit the dimension, you can use any additional item specified in the predicate, it works fine.
This scheme already looks more like schizophrenia, but it works and there are no bugs... Please ignore the drawback in the form of dozens of individual items for each location xD

**Comment by rtgxjzgsryksryydtyrkry** [comment]
Okay, there is no need to have several different types of item, just different amounts, so you can have up to 63 different locations and 1 return with 1 stack &1 empty slot

**Comment by RafalBerezin** [comment]
I finally found some time for this.

So far I added a pocket dimension privacy config, that can be accessed by using `/trigger PDConfig` command. (You also need the updated resource pack)

Let me know what do you think about this.

**Comment by RafalBerezin** [comment]
I added the ability to make the pocket dimension private and limit the portal uses. And since you're not responding, I'm closing this issue. You can always reopen or make a new one if you need something.

**Comment by rtgxjzgsryksryydtyrkry** [comment]
Sorry, I couldn't answer, I had problems. 
Thanks for the new features, they are very useful and this is exactly what this data pack was missing for me. I'm a little confused about whether commands are available to configure without permission. If possible, I would like to be able to prevent specific players from using config.

**Comment by RafalBerezin** [comment]
I'm glad you like it.

To clarify,

The global configuration can only be changed with OP permissions (more specifically with permissions to use a `/function ...` command). The personal configuration can be changed by every player, but only for themselves. In the global configuration, you can enforce some settings for all players.

I didn't implement a mechanic that allows to block the personal configuration only for specific players. Maybe I'll add it in the future, but I can't promise anything as I'm working on a different project right now.
