### ISSUE TITLE
Player Head or Username on top of the portal

### ISSUE THREAD

**Issue by CutePityOwl** [RafalBerezin/Pocket_Dimension#2]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An option (enable or disable) for displaying a player username or player head on top of the portal, this would be good especially for online servers

Also the datapack is very cool, good job!

**Comment by RafalBerezin** [comment]
I'm glad you like it.

And I think displaying the portal owner's name is a great idea. I'll definitely add it.
