### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by Alpha30811** [RafalBerezin/Pocket_Dimension#7]
As the title suggests 1.20.1 PLEASE!!!!!
This has been a good ver for Minecraft mods so please add it

**Comment by RafalBerezin** [comment]
As stated in another issue, support for Minecraft 1.20.1 is currently not planned.

**Comment by RafalBerezin** [comment]
This issue has been resolves in commit 6ba5f38 on the `backport/1.20.1` branch.
