### ISSUE TITLE
Fabric 1.20.1

### ISSUE THREAD

**Issue by TheBill75** [RafalBerezin/Pocket_Dimension#8]
Hi, Great mod! Is there a possibility you could make it for fabric 1.20.1? Thanks!

**Comment by RafalBerezin** [comment]
Hi, glad you like it!

Pocket Dimension relies on features added in Minecraft 1.20.2, so currently I'm not planning on releasing it for previous versions.
I might do it in the future, but only after I update it to newer versions.

**Comment by RafalBerezin** [comment]
This issue has been resolves in commit 6ba5f38 on the `backport/1.20.1` branch.
