### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by MasuSsovi** [RafalBerezin/Pocket_Dimension#9]
**Is your feature request related to a problem? Please describe.**
Want to add the mod to a 1.20.1 modpack, entering the dimension doesn't work other than that everything works

**Describe the solution you'd like**
A mod version in 1.20.1

**Describe alternatives you've considered**
Instructions to make the mod 1.20.1 compatible 

**Additional context**
N/A

**Comment by RafalBerezin** [comment]
Versions before 1.20.2 weren't planned, and I already said it in different issues.
But since a lot of people are asking for it, I'll see what I can do in my free time.

**Comment by RafalBerezin** [comment]
This issue has been resolves in commit 6ba5f38 on the `backport/1.20.1` branch.
